Added Buckeye Preparation
speechbrain/benchmarks pull request #19
Opened 2024-02-09 11:04 UTC by salah-zaiem

Added the preparation and its launch in the training script

2024-02-09 11:06 UTC, salah-zaiem commented
@Adel-Moumen

2024-02-13 09:48 UTC, Adel-Moumen requested changes
Hello Salah, 

Thanks for this PR. 

I left some early comments about this PR, they are mostly related to docstring. I will take a closer look next week. :)

2024-02-13 09:48 UTC, Adel-Moumen commented on benchmarks/MP3S/Buckeye/LSTM/buckeye_prepare.py
> +    >>> prepare_buckeye(buckeye_dir, save_folder)
you can remove this example since it won't work with the CI/CD

2024-02-13 09:48 UTC, Adel-Moumen commented on benchmarks/MP3S/Buckeye/LSTM/buckeye_prepare.py
> +def treat_word_file(wrd, buckeye_dir):
could you please add a docstring about this function / input args etc?

2024-02-13 09:48 UTC, Adel-Moumen commented on benchmarks/MP3S/Buckeye/LSTM/buckeye_prepare.py
> +def unzip_buckeye(buckeye_dir):
docstring please :p

2024-02-13 09:48 UTC, Adel-Moumen commented on benchmarks/MP3S/Buckeye/LSTM/buckeye_prepare.py
> +def prepare_csv(buckeye_dir, save_folder, csv_file, prefixes):
docstring please :p

2024-02-14 16:45 UTC, merged